# cargo-release config
tag-prefix = "v"
push = true
publish = true               # publish to crates.io
sign-commit = false
sign-tag = false
no-dev-version = false       # set next dev version after release
push-remote = "origin"

[package]
# optional: skip publishing certain packages in workspace
# skip = false
