sign-tag = true
push = true
publish = true
sign-commit = true
push-remote = "origin"
pre-release-commit-message = "chore: release version {{version}}"
tag-message = "release {{version}}"
pre-release-hook = [ "git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}" ]
