allow-branch = ["main"]

release = true
publish = true

tag = true
tag-message = "release {{version}}"
sign-tag = true

push = true
push-remote = "origin"
sign-commit = true

pre-release-commit-message = "chore(cargo-release): release version {{version}}"
pre-release-hook = [ "git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}" ]
